const { previewSettlement, uploadReceipt, getReceiptJob } = require("../../services/api")
Page({
  data: { tripId: "", currency: "CNY", amount: "", payer: "我", friend: "", allocationIndex: 0, allocationLabels: ["付款人自己买", "同行人自己买", "两人均分"], receiptPath: "", ocrCandidates: [], taxAmount: "", taxIncluded: true, adjustmentAmount: "", adjustmentType: 0, adjustmentLabels: ["公共优惠 / 退款", "个人优惠", "后续退税"], ocrStatus: "未上传" },
  onLoad(q) { this.setData({ tripId: q.tripId, currency: q.currency }) },
  chooseReceipt() { wx.chooseMedia({ count: 1, mediaType: ["image"], sourceType: ["camera", "album"], success: ({ tempFiles }) => wx.compressImage({ src: tempFiles[0].tempFilePath, quality: 80, success: ({ tempFilePath }) => { this.setData({ receiptPath: tempFilePath, ocrStatus: "等待上传识别" }); this.startOcr(tempFilePath) } }) }) },
  startOcr(filePath) { this.setData({ ocrStatus: "上传并识别中" }); uploadReceipt(this.data.tripId, filePath).then((job) => this.pollOcr(job.id)).catch(() => this.setData({ ocrStatus: "上传或识别失败，可手动录入" })) }, pollOcr(jobId) { getReceiptJob(jobId).then((job) => { const labels = { queued: "排队识别中", processing: "正在识别", needs_review: "待核对", failed: "识别失败，可手动录入" }; this.setData({ ocrStatus: labels[job.status] || job.status, ocrCandidates: job.status === "needs_review" ? job.candidates : [] }); if (job.status === "queued" || job.status === "processing") setTimeout(() => this.pollOcr(jobId), 1500) }) },
  onTaxIncluded(e) { this.setData({ taxIncluded: e.detail.value }) },
  onTax(e) { this.setData({ taxAmount: e.detail.value }) }, onAdjustment(e) { this.setData({ adjustmentAmount: e.detail.value }) }, onAdjustmentType(e) { this.setData({ adjustmentType: Number(e.detail.value) }) },
  onAmount(e) { this.setData({ amount: e.detail.value }) }, onPayer(e) { this.setData({ payer: e.detail.value }) }, onFriend(e) { this.setData({ friend: e.detail.value }) }, onAllocation(e) { this.setData({ allocationIndex: Number(e.detail.value) }) },
  preview() {
    const { tripId, currency, amount, payer, friend, allocationIndex, taxAmount, adjustmentAmount, adjustmentType, taxIncluded } = this.data
    if (!amount || !payer) return wx.showToast({ title: "请填写金额和付款人", icon: "none" })
    if (allocationIndex > 0 && !friend.trim()) return wx.showToast({ title: "请填写同行人", icon: "none" })
    const allocation = allocationIndex === 0 ? { [payer]: "1" } : allocationIndex === 1 ? { [friend]: "1" } : { [payer]: "0.5", [friend]: "0.5" }
    const participants = friend.trim() ? [payer, friend] : [payer]
    previewSettlement(tripId, { participants, settlement_currency: currency, expenses: [{ expense_id: "manual", payer_id: payer, items: [{ item_id: "manual-item", amount: { currency, amount }, allocation, tax_amount: taxAmount ? { currency, amount: taxAmount } : undefined, tax_included: taxIncluded }], adjustments: adjustmentAmount ? [{ adjustment_id: "adjustment", amount: { currency, amount: adjustmentAmount }, allocation: adjustmentType === 1 ? { [payer]: "1" } : allocation, reason: ["shared_discount_or_refund", "personal_coupon", "later_tax_refund"][adjustmentType], received_by: adjustmentType === 2 ? payer : undefined }] : [], actual_payment: { currency, amount } }] }).then((result) => { const transfer = result.transfers[0]; wx.showModal({ title: "分账预览", content: transfer ? `${transfer.from_participant_id} 需转给 ${transfer.to_participant_id} ${transfer.amount.amount} ${transfer.amount.currency}` : "无需转账", showCancel: false }) }).catch((e) => wx.showToast({ title: e.message || "预览失败", icon: "none" }))
  }
})